### ISSUE TITLE
Can't Get Notifications When App Is Closed

### ISSUE THREAD

**Issue by farzin680** [chabokpush/chabok-client-ios#11]
Hi ,
I Did Done Everything Explained On The Documentations For IOS Devices In The Apple Developer Center , XCode , ...

I Get Notifications When App is In Background or Is In Foreground , But When App Is Closed No Notification Is Received !

Any Suggestions ?!

**Comment by Husseinhj** [comment]
Do you set [Apple push notification setting ](https://doc.chabokpush.com/panel/settings.html#%D9%BE%D9%84%D8%AA%D9%81%D8%B1%D9%85%D9%87%D8%A7)in the Chabok panel?

If you set the setting, Did you **turned** production switch button (in Chabok panel setting) to **ON or OFF** in Apple push notification **settings**?

> `NOTE`: For running the app in **debugging mode**, you should set Apple push notification setting for **development certification** (Sandbox) and turn production switch button to **OFF**. For apple **production** push notification, you should create **IPA** for enterprise and download from your direct link or **AppStore** to install the app and send the push notification and turn production switch button to **ON**.

**Comment by farzin680** [comment]
Thanks For Your Answer,

Actually I Found The Solution.
The Problem Is That We Have To Turn "Apple Push Notification Center" - "سرور علمیاتی اپل" To Off And Then We're All Set !

Thank You Again.
