### ISSUE TITLE
Getting notification with Data

### ISSUE THREAD

**Issue by aminjalalian** [chabokpush/chabok-client-ios#13]
I want to get Data from notification , but it does not work correctly and leads the app to crash
What should i do ?

**The Error :**
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'unable to serialize userInfo: Error Domain=NSCocoaErrorDomain Code=3851 "Property list invalid for format: 200 (property lists cannot contain objects of type 'CFNull')" UserInfo={NSDebugDescription=Property list invalid for format: 200 (property lists cannot contain objects of type 'CFNull')}'
*** First throw call stack:
(0x182c3ed8c 0x181df85ec 0x18d12e6f8 0x100b2a058 0x100b28320 0x100b33e2c 0x100b4c388 0x100b4bf24 0x100b1da64 0x182b77b34 0x182b83554 0x182b7762c 0x1832b172c 0x1832b6ee4 0x1832b2d58 0x182bed9f4 0x182be7404 0x182be6c2c 0x182be479c 0x182b04da8 0x184aea020 0x18cb24758 0x100ae78f0 0x182595fc0)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by Husseinhj** [comment]
Do you want to get `data` from `PushClientMessage` class or `didReceiveRemoteNotification` delegate method?

To get the `data` from the `PushClientMessage` use instance of this class and call `message.data`.

In `didReceiveRemoteNotification` use `userInfo` parameters which means your message data is in `[userInfo valueForKey:@"data"]`

**Comment by aminjalalian** [comment]
`PushClientMessage`
i got data from `message.data`
when the `pushClientManagerDidReceivedMessage(_:)` finished , app will crash

**Comment by Husseinhj** [comment]
Did your code crash the app or Chabok framework?

> I want to get Data from notification, but it does not work correctly and leads the app to crash
What should i do ?

As for you say, I got you can't get `data` from the Chabok message.

**Comment by aminjalalian** [comment]
I thing Chabok framework

i get data, after pushClientManagerDidReceivedMessage(_:) method finished , app will crash

**Comment by Husseinhj** [comment]
Could you give us your Message **payload**? It helps us.

**Comment by aminjalalian** [comment]
The problem solved
**Body** should not be **null**

Thanks
