### ISSUE TITLE
دلیل نمایش دوباره ناتیف هنگام باز شدن اپ چیست؟

### ISSUE THREAD

**Issue by SaeedSkf** [chabokpush/chabok-client-ios#14]
من با تنظیمات پیشفرض چابک را روی پروژه پیاده کردم. هنگامی که برنامه بسته است و روی ناتیف تپ می شود٬ برنامه باز می شود اما پس از باز شدن دوباره همان ناتیف دریافت می شود. اگر این ناتیف ها زیاد باشد بسیار زننده می شود و تمام ناتیف ها دوباره اعلان میشوند. آیا برای جلوگیری از این مورد نیاز به تنظیمات خاصی هست؟

**Comment by Husseinhj** [comment]
<div dir='rtl'>
مکانیز چابک با سرویس‌های پوش نوتیفیکیشن همانند وان‌سیگنال متفاوت است. چابک ابتدا اگر دستگاه به چابک متصل باشه پیام را برای کاربر ارسال می‌کند (از طریق کانکش مستقیمی که دارد)، اگر کاربر در برنامه نباشد و اپ بسته باشد چابک اقدام به ارسال پوش نوتیفیکیشن می‌کند تا کاربر را مطلع سازد که یک پیامی دارد. این موضوع برای این بوده که دیتا شما وارد سرویس‌های خارجی نشود

>  برنامه باز می شود اما پس از باز شدن دوباره همان ناتیف دریافت می شود.

وقتی برنامه باز شود شما پیام چابک را دریافت می‌کنید که از پوش‌نوتیفیکشن جدا است. 

> آیا برای جلوگیری از این مورد نیاز به تنظیمات خاصی هست؟

برای عدم نمایش نوتیفیکیشن چابک از متد زیر استفاده کنید 
که چابک به صورت خودکار در صورت پیاده سازی متد فوق از نمایش نوتیفیکیشن برای پیام درون‌برنامه چابک جلوگیری می‌کند.
</div>


```objective-c
-(void) pushClientManagerUILocalNotificationDidReceivedMessage:(PushClientMessage *)message {
    //If this method was implemented the Chabok prevent showing local notification and give the Chabok message to the developer to create own local notification
}
```

**Comment by Husseinhj** [comment]
من این ایشو رو می‌بند،‌ اگر مشکل شما حل نشده دوباره ایشو رو باز کنین تا درموردش بیشتر صحبت کنیم.

**Comment by Husseinhj** [comment]
<div dir='rtl'>
همچنین از طریق api هم می‌تونید تعیین کنین که پیام به چه صورت به کاربر برسه

به صورت in-app یا live ارسال بشه
</div>
