### ISSUE TITLE
registerUser method's callback doesn't call

### ISSUE THREAD

**Issue by pouyayarandi** [chabokpush/chabok-client-ios#15]
Hi
I want to do something with installation id when user registered in chabokpush. so I put my codes in the `registerUser`'s callback in this way:
```swift
guard let manager = PushClientManager.default() else { return }
manager.registerUser(userId) { (_, _, _) in
            print(manager.getInstallationId() ?? "??")
}
```
but it doesn't work. not even prints `??`.

1) why?
2) could you describe about 3 arguments `(Bool, String?, Error?)` that callback gives.
Thanks

**Comment by Husseinhj** [comment]
Did you call the Chabok `registerApplication` [method](https://doc.chabokpush.com/ios/setup.html#%DB%B1--%D9%85%D9%82%D8%AF%D8%A7%D8%B1%D8%AF%D9%87%DB%8C-%D8%A7%D9%88%D9%84%DB%8C%D9%87)?

```swift
manager?.registerApplication("APP_ID", apiKey: "API_KEY", userName: "SDK_USERNAME", password: "SDK_PASSWORD")
```

**Comment by pouyayarandi** [comment]
@Husseinhj 
Yes, in `AppDelegate` class when app launches, I called `registerApplication` method. I currently use
`manager.registerUser(userId)`
but the problem is that I can't get installation id for first time after app installation.

**Comment by Husseinhj** [comment]
> could you describe about 3 arguments (Bool, String?, Error?) that callback gives.

```swift
self.manager.registerUser("USER_ID") { (isRegisterd, userId, error) in
     if(isRegisterd && error == nil){
          print("Registered : \(userId)")
     } else {
          print("Not registered, Error : \(error)")
     }
}
```

In this comment you said :
> but it doesn't work. not even prints ??.

and

> but the problem is that I can't get installation id for first time after app installation.

I don't understand, `registerUser` **callback** doesn't work or `getInstallationId()` in callback method is nil.

**Comment by pouyayarandi** [comment]
`registerUser` callback doesn't work and I should call my method (for working with installation id) out of callback. In first time of launching app after installation, we don't have installation id so my method can not perform.

**Comment by Husseinhj** [comment]
This callback should be invoked. 
Please **clone** the [Chabok-Starter](https://github.com/chabokpush/chabok-starter-ios) project and run see the **debugger log**.
I did update this repo with adding callback of `registerUser` method. If it's work you should give me a flow of using Chabok in your project and try to help you why in your scenario callback didn't invoke.

**Comment by pouyayarandi** [comment]
I cloned your test project and wrote my code like that
```swift
manager.registerUser(userId) { (isRegistered, uid, error) in
      if isRegistered && error == nil {
          print("registered")
      } else {
          print("not registered: \(error!)")
          print("uid: \(uid ?? "nil")")
      }
}
```
but it not works again and prints nothing.
about my flow; I call this method in a parser method which means when our server respond to my request I'll  call your register method in callback.

**Comment by Husseinhj** [comment]
> I cloned your test project and wrote my code like that

In Starter-Project, Is the register method callback invoked?

> about my flow; I call this method in a parser method which means when our server respond to my request I'll call your register method in callback.

The `registerUser` should call in 2 classes in normal state of applications which has login page.
1. **AppDelegate** class: You should call this method if the user was registered before then call this method to connect the Chabok server.
2. **Login** class: if the user was not registered yet so you show login ViewController and after verifying the user call this method.

**Comment by pouyayarandi** [comment]
> In Starter-Project, Is the register method callback invoked?

Yes, in your test project register method invoked.

> The registerUser should call in 2 classes in normal state of applications which has login page.
> 
> AppDelegate class: You should call this method if the user was registered before then call this method to connect the Chabok server.
> Login class: if the user was not registered yet so you show login ViewController and after verifying the user call this method.

didn't know it. I'll test that

**Comment by Husseinhj** [comment]
> Yes, in your test project register method invoked.

I think it's about the **cycle** of your implementation or when you call this method, Your class isn't in **memory** anymore and your callback would not be invoked.

> didn't know it. I'll test that

This method creates the user with `userId` and connects to the Chabok server If `userId` was equal of the first time call this method just try to **connect** to the server.

**Comment by pouyayarandi** [comment]
> I think it's about the cycle of your implementation or when you call this method, Your class isn't in memory anymore and your callback would not be invoked.

I test that but it not works. neither in login view nor the view that opens after login ended.

**Comment by Husseinhj** [comment]
> I test that but it not works. neither in login view nor the view that opens after login ended.

Did you test in AppDelegate class?

**Comment by pouyayarandi** [comment]
> Did you test in AppDelegate class?

in `AppDelegate`, I don't have `userId` for first time after installation

**Comment by Husseinhj** [comment]
> in AppDelegate, I don't have userId for first time after installation

I know that just want to find out callback will be invoked or not. Test with const `userId` for the first time **launch**.

Why are you using the `timer.invalidate()` method?
Did you call the Chabok `registerUser` method in timer scope?

**Comment by pouyayarandi** [comment]
> I know that just want to find out callback will be invoked or not. Test with const userId for the first time launch.

Ok, I'll test that

> Why are you using the timer.invalidate() method?

no, I used timer just for log. 

> Did you call the Chabok registerUser method in timer scope?

no, I just called `invalidate()` of timer in callback

**UPDATE:** it works in `AppDelegate`

**Comment by Husseinhj** [comment]
@pouyayarandi I think it's not related to the Chabok framework and I'll close this issue.
If you want to fix this, give me more information about your information **privately** and help you if I can.
