### ISSUE TITLE
Rich notification not showing image

### ISSUE THREAD

**Issue by pouyayarandi** [chabokpush/chabok-client-ios#16]
Hi again :)
I implemented rich notification in our project but when a rich push sends, it just showing image in app (on launching) and when we aren't in app it shows as a normal push (without image). I followed instructions of this link:
https://doc.chabokpush.com/ios/rich_notification.html
thanks

**Comment by Husseinhj** [comment]
Could you give us your notification payload here?

Did you put these keys in your [notification payload](https://doc.chabokpush.com/rest-api/send-push.html#%D9%BE%D8%A7%D8%B1%D8%A7%D9%85%D8%AA%D8%B1%D9%87%D8%A7%DB%8C-%D8%A7%D8%B9%D9%84%D8%A7%D9%86-notification)?

```js
{
  ...
  "notification":{
    ...
    "mutableContent": true,
    "category": "categoryName"
  }
}
```

**Comment by pouyayarandi** [comment]
Thanks. resolved
in our payload, `mutableContent` was `false`.
