### ISSUE TITLE
test push in debug mode

### ISSUE THREAD

**Issue by mohammadFirouzi** [chabokpush/chabok-client-ios#18]
push notification just works in release versions and i need to test push notifications in debug mode (to get data and ...) !
is there any way to do it ?

**Comment by Husseinhj** [comment]
> push notification just works in release versions

Please, read the [troubleshooting](https://doc.chabokpush.com/ios/troubleshoot.html#%D8%B3%D9%88%D8%A6%DB%8C%DA%86-%D8%B3%D8%B1%D9%88%D8%B1-%D8%B9%D9%85%D9%84%DB%8C%D8%A7%D8%AA%DB%8C-%D8%A7%D9%BE%D9%84-%D8%B1%D8%A7-%D8%AF%D8%B1-%D9%BE%D9%86%D9%84-%D8%A8%D9%87-%D8%AF%D8%B1%D8%B3%D8%AA%DB%8C-%D8%AA%D9%86%D8%B8%DB%8C%D9%85-%DA%A9%D9%86%DB%8C%D8%AF) section for the iOS platform.

![image](https://user-images.githubusercontent.com/27139702/48965881-518ef600-efdb-11e8-920f-251be8edc288.png)

For debugging mode put your apple sandbox push notification cert and key in Chabok panel and turn `سرور عملیاتی` switch button to off.

![image](https://user-images.githubusercontent.com/27139702/48965894-e09c0e00-efdb-11e8-8171-d1eeef291951.png)
