### ISSUE TITLE
تفاوت Sandbox و Production

### ISSUE THREAD

**Issue by e-sh** [chabokpush/chabok-client-ios#19]
<p dir="rtl">با سلام</p>
<p dir="rtl">هنگامی که برنامه را روی Production قرار می دهیم حتی کاربر هم اضافه نمی شود و باید حتما حساب مربوطه را تهیه کند؟
امکان ارتقا از  Sandbox به Production برای کاربر وجود دارد تا اطلاعات Sandbox را هم داشته باشد؟</p>

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">هنگامی که برنامه را روی Production قرار می دهیم حتی کاربر هم اضافه نمی شود و باید حتما حساب مربوطه را تهیه کند؟</p>
</blockquote>
<p dir="rtl">بله، باید از پنل رایگان (سندباکس) خودتون<a href="https://doc.chabokpush.com/panel/settings.html#%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D8%AD%D8%B3%D8%A7%D8%A8-%D8%B9%D9%85%D9%84%DB%8C%D8%A7%D8%AA%DB%8C"> درخواست حساب عملیاتی (پروداکشن) رو ثبت کنین</a> و پس از تماس با شما حساب کاربری عملیاتی برای 
شما ساخته میشه. نکته: داده‌های این دو پنل کاملا جدا از هم هستن.</p>
<blockquote dir="rtl">
<p dir="rtl">امکان ارتقا از Sandbox به Production برای کاربر وجود دارد تا اطلاعات Sandbox را هم داشته باشد؟</p>
</blockquote>
<p dir="rtl">اگه منظور شما انتقال اطلاعات از محیط رایگان (سندباکس) به محیط عملیاتی (پروداکشن) هست؛ خیر، داده‌های محیط رایگان <a href="https://doc.chabokpush.com/ios/required.html#%D8%A7%DB%8C%D8%AC%D8%A7%D8%AF-%D8%AD%D8%B3%D8%A7%D8%A8-%DA%86%D8%A7%D8%A8%DA%A9">قابل مهاجرت به محیط عملیاتی نیست</a> و برای انتقال کاربراتون به محیط عملیاتی باید نسخه جدید بدین</p>
