### ISSUE TITLE
PushClientManagerDelegate methods not being called

### ISSUE THREAD

**Issue by sepbehroozi** [chabokpush/chabok-client-ios#5]
Hi,
As the Chabok doc says, I have registered user at Chabok when the apple push notification permission dialog needed to be shown. here is the code (in first ViewController after showing some message about push notification):
```swift
let userId = User.currentUser?.id ?? generateRandomId()
(UIApplication.shared.delegate as? AppDelegate)?.manager?.registerUser(userId)
```

And here is my `AppDelegate` `didFinishLaunchingWithOptions` func:
```swift
self.manager = PushClientManager.default()
PushClientManager.setDevelopment(isDebug)
manager?.registerApplication(ChabokCredentialInfo.appID, apiKey: ChabokCredentialInfo.sdkKey, userName: ChabokCredentialInfo.username, password: ChabokCredentialInfo.password)
manager?.addDelegate(self)
manager?.enableLocationOnLaunch = true
```
And other `AppDelegate` function as Chabok doc says:
```swift
func application(_ application: UIApplication, didReceive notification: UILocalNotification) {
    self.manager?.application(application, didReceive: notification)
}

func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any]) {
    self.manager?.application(application, didReceiveRemoteNotification: userInfo)
}

func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
    self.manager?.application(application, didFailToRegisterForRemoteNotificationsWithError: error)
}

func application(_ application: UIApplication, didRegister notificationSettings: UIUserNotificationSettings) {
    self.manager?.application(application, didRegister: notificationSettings)
}

func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
    print("APNs token retrieved: \(deviceToken as NSData)")
    self.manager?.application(application, didRegisterForRemoteNotificationsWithDeviceToken: deviceToken)
}
```

So here is the problem, with this configs and registration flow, every push notification is being arrived from the APNs channel, not Chabok exclusive connection, event when the app is in foreground. and no functions of `PushClientManagerDelegate` is being called for incoming push notifications. this issue cause the app to have no control over incoming push notifications.

As a workaround I put this code before registering user to Chabok: 
```swift
if #available(iOS 10.0, *) {
    let authOptions: UNAuthorizationOptions = [.alert, .badge, .sound]
    UNUserNotificationCenter.current().requestAuthorization(
        options: authOptions,
        completionHandler: {_, _ in })
} else {
    let settings: UIUserNotificationSettings =
        UIUserNotificationSettings(types: [.alert, .badge, .sound], categories: nil)
    UIApplication.shared.registerUserNotificationSettings(settings)
}

UIApplication.shared.registerForRemoteNotifications()

let userId = User.currentUser?.id ?? generateRandomId()
(UIApplication.shared.delegate as? AppDelegate)?.manager?.registerUser(userId)
```

**Comment by Husseinhj** [comment]
@3pehrbehroozi I didn't understand what is your problem?
1) You want to have delegate method when APNs message was received ?
As about i said before, `didReceiveRemoteNotification` called when user was tapped on the APNs notification (**Foreground**/**Background**).
In `UNUserNotificationCenter` class there is `willPresent notification: ` delegate method which called when a notification is delivered to a **foreground** app.

```swift
//Notification handling for iOS 10
@available(iOS 10.0, *)
func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
        //Called when a notification is delivered to a foreground app.
}
```
2) If you could not receive `Chabok Message`, You should Use this code:

``` swift
func pushClientManagerDidReceivedMessage(message: PushClientMessage!) {
    //Called when Chabok push received.
}    
```

At the end use `PushClientManager` **singleton** pattern in other VC user `PushClientManager.default().registerUser(userId)` instead of use`(UIApplication.shared.delegate as? AppDelegate)?.manager?.registerUser(userId)`

**Comment by sepbehroozi** [comment]
What i understood from Chabok doc and your guidance was `pushClientManagerDidReceivedMessage` should be called in two different ways, one is when the app is in foreground and the other way is when the app was in background and user clicks the notification received by APNs. So i put my code in `pushClientManagerDidReceivedMessage` and expect the message to be given there finally.
But this is not happening when i register user with just `PushClientManager.default().registerUser(userId)` and the `pushClientManagerDidReceivedMessage` func will not be called.

As a proof, you said the little rocket icon in panel will send an APNs test notification to the user, and user will see the test notification **if the app is in background**. when i register user with just `PushClientManager.default().registerUser` (without the workaround I said) event the test notification will be presented to the foreground app.

> At the end use PushClientManager singleton pattern in other VC user PushClientManager.default().registerUser(userId) instead of use(UIApplication.shared.delegate as? AppDelegate)?.manager?.registerUser(userId)

Yes of course this was a bad code! Thanks for your suggestion.

**Comment by Husseinhj** [comment]
In Chabok documents see [ManageNotification](https://doc.chabokpush.com/ios/notification.html) section we describe how to use each method for manage click on Notification alert.

But i say again how ChabokPush works. `pushClientManagerDidReceivedMessage` will invoke when your app was connected (It doesn't  matter app is in **Foreground**/**Backgroud**) to **ChabokServer** and You have a message. To show your own LocalNotification and skip show Chabok UILocalNotification when ChabokMessage was recieved, use this method:

``` swift
func pushClientManagerUILocalNotificationDidReceivedMessage(_ message: PushClientMessage!) {
    //If you implement this method, You shoud show user UILocalNotification.
    let localNotification = UILocalNotification()
      
    localNotification.timeZone = NSTimeZone.local
    localNotification.alertBody = message.messageBody
    localNotification.alertAction = "OK"
    localNotification.userInfo = message.toDict()
        
    UIApplication.shared.scheduleLocalNotification(localNotification)
}
```

`didReceive notification:` called when user tap on `UILocalNotification`:

```swift
func application(_ application: UIApplication, didReceive notification: UILocalNotification) {
    //Called when user tap on UILocalNotification.
}
```

`didReceiveRemoteNotification` called when user was tap on the **APNs** notification (**Foreground**/**Background**).
In `UNUserNotificationCenter` class there is `willPresent notification: ` delegate method which called when a notification is delivered to a **foreground** app.

So you said:
> As a proof, you said the little rocket icon in panel will send an APNs test notification to the user, and user will see the test notification if the app is in background.

I said `little rocket icon in panel will send an APNs test notification to the user` it doesn't matter you are connected to Chabok (You show register to Chabok and has APNs token) or Application state(Foreground, Background or Terminated), Just send APNs test notification. and as about is said  `didReceiveRemoteNotification` called when user was tap on the **APNs** notification (**Foreground**/**Background**).

At the end you should know when Chabok send **ChabokMessage**, **PushNotification (Cloud Messaging)** and **SMS**. If you was connected to ChabokServer, You will receive **ChabokMessage**. If you was not connected to ChabokServer for any reason (App was terminated or app is in background and after 3 min was killed by iOS ,...) you will get **PushNotification (Cloud Messaging)** after user open the app and connect to ChabokServer will get  **ChabokMessage**.
