### ISSUE TITLE
I have done every thing but it  does not work

### ISSUE THREAD

**Issue by amirtutunchi** [chabokpush/chabok-client-ios#9]
hi 
i do every thing based on your doc and sample project but i cant connect to server and all i got in console is : URL: "cydia://package/com.example.package" - error: "This app is not allowed to query for scheme cydia" 
i added Allow Arbitrary Loads to true but still it does not fixed

**Comment by Husseinhj** [comment]
This error doesn't concern to the Chabok framework.

The Chabok log is like this :
```
CHABOKPUSH LOG : ----------------------

 [-[PushClientManager application:didFailToRegisterForRemoteNotificationsWithError:]]

----------------------
```
Please, explain about what exactly is your code doing?
I think your code checking device was jailbreak or not

For see the Chabok logs, set `enableLog` property to `YES/true`
